### ISSUE TITLE
Shares with spaces in name are not handled correctly

### ISSUE THREAD

**Issue by dmchell** [vivami/SauronEye#5]
Hopefully it's self explanatory, but if the share name has a space in it, the searcher is not parsing the path correctly. I didn't give in to it but my guess is this is down to how you're delimiting the directories list from arguments.

**Comment by vivami** [comment]
Thanks for reporting this bug Dominic, you're right. `Mono.Options` is not handling the combination of spaces and backslashes well. I have to investigate a bit on how to overcome this when I have a bit more time. 

A workaround for now is to use quotes around the path, and escape the last quote with a backslash, like so: 
`SauronEye.exe -d "\\HOSTNAME\path with space\\" --filetypes [...]`

Anyways, yet another argument for me to make unit tests...🙄

**Comment by vivami** [comment]
The way mono handles cases like this is by passing the argument multiple times: 

`SauronEye.exe -d "C:\Users\user\Path with a space" -d "\\SOME NETWORK DRIVE\C$" --filetypes .txt --keywords password pass*`. 

Changing this behaviour would require changes to the `Mono.Options` lib, which for obvious reasons I don't want to do. 

I've clarified this use case like this with a usage example in the README:
https://github.com/vivami/SauronEye/commit/c04b65161510d3815c3ef3ca4f71ac639086083f

I'll close this issue. If there are any other issues, please don't hesitate to open one again.

**Comment by dmchell** [comment]
Thanks!
