### ISSUE TITLE
Illegal character error when using share with dollar sign

### ISSUE THREAD

**Issue by stanhegt** [vivami/SauronEye#6]
Scanning a share with a dollar sign in the name triggers the following exception (note, this only happens when doing a content / keywords scan):

\\hostname\sharename$\Tools\x86\Preflight\wmi_format.vbs. Continuing with the next directory.
[-] Some unknown exception Illegal characters in path. occured while processing \\hostname\sharename$\Tools\x86\wimscript.ini. Continuing with the next directory.

**Comment by vivami** [comment]
Thanks for reporting this bug, Stan. I can reproduce the bug. I prepend `\\?\` to file paths to be able to handle > 260 chars in a path. But apparently `FileInfo` (Windows) functionality breaks when you have a dolla in fileshare name.

I hope to get around to fixing it later this week.

**Comment by vivami** [comment]
This should be fixed in https://github.com/vivami/SauronEye/commit/769c3b785fc256532b0aa46d96766361f2fc574f. New release is [0.0.8](https://github.com/vivami/SauronEye/releases/tag/0.0.8).
